/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function nativeRegisterDispatcher(dispatcher: (...args: any[]) => any): void
export declare function nativeSetConfig(config: any): Promise<void>
export declare function nativeLaunch(): Promise<void>
export declare function nativeShutdown(timeoutMs?: number | undefined | null): Promise<void>
export declare function nativeRuntimeInfo(): any
export declare function nativeRegisterWorkflow(name: string, callbackId: string): void
export declare function nativeRunWorkflow(name: string, args: any): Promise<string>
export declare function nativeStartWorkflow(name: string, args: any, params?: any | undefined | null): Promise<string>
export declare function nativeRunStep(workflowId: string, name: string, callbackId: string): Promise<any>
export declare function nativeGetResult(workflowId: string, timeoutMs?: number | undefined | null): Promise<any>
export declare function nativeGetStatus(workflowId: string): Promise<any>
export declare function nativeCancelWorkflow(workflowId: string): Promise<boolean>
export declare function nativeResumeWorkflow(workflowId: string, queueName?: string | undefined | null): Promise<boolean>
export declare function nativeForkWorkflow(workflowId: string, options?: any | undefined | null): Promise<string>
export declare function nativeSleep(workflowId: string, durationMs: number): Promise<number>
export declare function nativeSend(workflowId: string | undefined | null, destinationId: string, message: any, topic?: string | undefined | null): Promise<void>
export declare function nativeRecv(workflowId: string, topic?: string | undefined | null, timeoutMs?: number | undefined | null): Promise<any>
export declare function nativeSetEvent(workflowId: string, key: string, value: any): Promise<void>
export declare function nativeGetEvent(workflowId: string | undefined | null, targetWorkflowId: string, key: string, timeoutMs?: number | undefined | null): Promise<any>
export declare function nativeWriteStream(workflowId: string, key: string, value: any): Promise<void>
export declare function nativeCloseStream(workflowId: string, key: string): Promise<void>
export declare function nativeReadStream(workflowId: string, key: string, snapshot?: boolean | undefined | null, fromOffset?: number | undefined | null): Promise<any>
export declare function nativeRegisterQueue(name: string, options?: any | undefined | null): Promise<any>
export declare function nativeListWorkflows(filter?: any | undefined | null): Promise<any>
export declare function nativeListWorkflowSteps(workflowId: string): Promise<any>
export declare function nativePatch(workflowId: string, patchName: string): Promise<boolean>
export declare function nativeDeprecatePatch(workflowId: string, patchName: string): Promise<boolean>
export declare function nativeCompleteCallback(requestId: string, ok: boolean, value?: any | undefined | null, error?: string | undefined | null): void
